# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            韩宏敏
tagline:          '韩宏敏的博客'
description:      '一个无知的屁民'
url:              http://hanhongmin.com
baseurl:          /

author:
  name:           '韩宏敏'
  url:            http://hanhongmin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kainecy
